using Cipher.Ciphers;
using Cipher.Text;
using System;

namespace CipherPrompt
{
    class Program
    {
        static bool Debug = false;
        static void Main(string[] args)
        {
#if DEBUG
            Debug = true;
#endif
            DateTime Start = DateTime.Now;

            Substitution<QuadgramScoredLetterArray> Sub = new Substitution<QuadgramScoredLetterArray>("SYIEZLKKZRIVPYIMPQVZFSLMLCKILVWMPFUBIVSZPYHLZEPMLEVULERLMOQPPYIHKFGIMMFKYICHIVDIITHCLZEPFVLEZICPYLPPYIGFKNIKZIMSFQCVOIJQZUBCWVIPIUPIVZGSIQMIVPYIDMYISLMHLZEPIVFELHFHCLKOFLKVKLPYIKPYLELMPKIPUYIVULERLMLEVPYIHZNDIEPMQMIVOWPYIDLMPIKSIKIRIKWVZGGIKIEPGKFDPYIFEIMSIQMIPFVLWEFSPYIWOKZENDIPYIHZNDIEPMZLMBGFKMFGPUYLCBWOCFFVKIVMLENQZEILEVDQMPLKVWICCFSFUYKIMGKFDPYIMFZCMFGZPLCWZDZTPYIDSZPYCZEMIIVFZCOFZCIVLEVLNIVZELBIPPCIHKFHIKCWHKIHLKIVPYIMIHLZEPMLKIZEVZMPZENQZMYLOCIGKFDPYIFEIMQMIVFEPYIFKZNZELCLEVPYIUFHWZMDFKICZBICWPFOIOIPKLWIVOWLULKICIMMOKQMYMPKFBIFKLDZMHCLUIVYZNYCZNYPPYIHKFGIMMFKMIIMJQZUBCWSYIEDWPZKIVIWIMYLRIDZMMIVLPFEILEVZYLRIDLVIIEFQNYVICZOIKLPIDZMPLBIMPFUFERZEUIPYIDPFDFRIDWMPQVZFPFPYILPPZUSYIKIPYICZNYPZMOIPPIKGKFDPYIKIZYLRILRZISFGPYIUZPWLEVLKIDZEVIKFGGKIIVFDPYIWMPZCCZEMZMPPYLPZMCIIHYIKIZEPYIUICCLKOQPPYLPNZRIMDILEFPYIKGKIIVFDPYIGCZUBIKZENULEVCIMULMPVIIHMYLVFSMSYZUYYZVIDWFPYIKSFKBZGZULEEFPOIGKIIHIKYLHMMYIULE");
            Console.WriteLine(Sub.Crack());
            
            if(Debug)
            {
                DateTime End = DateTime.Now;
                TimeSpan Duration = End - Start;
                Console.WriteLine("Took {0} seconds to complete", Duration.TotalSeconds);
                Console.WriteLine("Press [enter] to exit");
                Console.ReadLine();
            }

        }
    }
}
